config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord 
  validates :body, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord 
  validates :username, presence: true, length: { minimum: 3, maximum: 30 }
  has_secure_password
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user 
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to continue"
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user, only: [:index]
  def index 
    @message = Message.new
    @messages = Message.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController 
  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel", message: message_render(message)
    end
  end

  private
  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: { message: message })
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 
  before_action :login_redirect, only: [:new, :create]
  def new 
    @user = User.new
  end
  
  def create 
    user = User.find_by(username: params[:session][:username])
    if user and user.authenticate(params[:session][:password])
      flash[:success] = "Logged in successfully"
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now[:error] = "Invalid credentials. Try again!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:error] = "Logged out successfully"
    redirect_to login_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

  def login_redirect
    if logged_in?
      flash[:error] = "You are already logged in."
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui black center aligned icon header ">
  <i class="ui circular red paper plane outline
  icon custom"></i>
  Welcome to ImChat App!
</h2>
<br><br>
<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card set-height">
      <div class="ui content" id="messages">
        <div class="ui feed" id="message_container">
          <%= render @messages %>
        </div>
      </div>
    </div>
    <div class="extra content">
      <%= form_with(url: message_path, scope: :message, remote: true) do |f| %>
      <div class="field">
        <div class="ui fluid icon right input">
          <%= f.text_field :body %>
          <%= f.button '<i class="bordered inverted green edit icon"></i>'.html_safe %>
        </div>
      </div>

      <% end %>
    </div>
  </div>



  <div class="four wide column">
    <div class="ui fluid raised card set-height">
      <div class="ui content">
        <div class="ui medium inverted vertical menu">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |key, message| %>
<div class="ui <%= key %> message">
  <i class="close icon"></i>
  <div class="header">
    <%= message %>
  </div>
</div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui inverted small menu">
  <div class="ui container">
    <a class="active item">
      Chatroom
    </a>
    <a class="item">
      Messages
    </a>
    <div class="right menu">
      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
          <% if logged_in? %>
          <%= link_to "Logout", logout_path, method: :delete, class: 'item' %>
          <% else %>
          <a class="item">Signin</a>
          <a class="item">Signup</a>
          <% end %>

        </div>
      </div>
      <% if !logged_in? %>
      <div class="item">
        <div class="ui primary button">Sign Up</div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>ImChat</title>
  <%= favicon_link_tag asset_path('favicon.ico') %>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/navigation' %>

  <div class="ui container">
    <%= render 'layouts/flash' %>
    <%= yield %>
  </div>
</body>

</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %></em>: <%= message.body %>
    </div>
  </div>
</div>